const BANNED_DOMAINS=["gmail.com","outlook.com","hotmail.com","yahoo.com","icloud.com","aol.com","protonmail.com","zoho.com","mail.com"];
const CMS={industries:[
{title:"Technology, Telecom & Cloud SaaS",summary:"CIOs, CISOs, cloud architects, DevOps, and software buyers.",description:"Enterprise cloud, generative AI, zero-trust security."},
{title:"Automotive & Next-Gen Mobility",summary:"OEM R&D, tier-1 suppliers, battery engineers, fleet heads.",description:"EVs, ADAS, battery supply chains."},
{title:"Healthcare & Life Sciences",summary:"Physicians, P&T committees, nurses, lab directors.",description:"High-compliance specialist research."},
{title:"BFSI",summary:"PMs, PE partners, underwriters, wealth advisors.",description:"Capital allocators and treasury diligence."},
{title:"CPG / FMCG & Retail",summary:"Shoppers, category buyers, store managers.",description:"Omnichannel, shelf tests, conjoint."},
{title:"Manufacturing & Industrial",summary:"Plant GMs, procurement, automation heads.",description:"Factory operations and robotics."},
{title:"Energy & Utilities",summary:"Grid planners, renewable developers, plant engineers.",description:"Utility and BESS research."},
{title:"Construction & Real Estate",summary:"GCs, developers, architects, PMs.",description:"Specification and delay attribution."},
{title:"Education & EdTech",summary:"Provosts, campus CIOs, superintendents.",description:"LMS and upskilling studies."},
{title:"Media, Streaming & Ad-Tech",summary:"Planners, programmatic buyers, CMOs.",description:"CTV lift and media planning."},
{title:"Oil, Gas & Petrochemicals",summary:"Drilling supervisors, refinery managers.",description:"Upstream and ESG methane."},
{title:"Professional Services & Legal",summary:"Managing partners, Big 4, GCs.",description:"Legal spend and advisory fees."}
]};
function toggleMobile(){const m=document.getElementById("mobileMenu");if(m)m.style.display=m.style.display==="block"?"none":"block"}
function openRespondentModal(tab){const modal=document.getElementById("respondentModal");if(!modal)return;modal.classList.add("open");document.body.style.overflow="hidden";switchPanelTab(tab||"register");const s=document.getElementById("respSuccessNotice");if(s)s.hidden=true}
function closeRespondentModal(){const modal=document.getElementById("respondentModal");if(!modal)return;modal.classList.remove("open");document.body.style.overflow="auto"}
function switchPanelTab(tab){const reg=document.getElementById("respondentRegisterForm");const login=document.getElementById("respondentLoginForm");if(!reg||!login)return;const isReg=tab==="register";reg.hidden=!isReg;login.hidden=isReg}
function handleRespondentRegister(e){e.preventDefault();const email=document.getElementById("resp_email").value.trim().toLowerCase();const domain=email.split("@")[1]||"";const notice=document.getElementById("emailErrorNotice");if(BANNED_DOMAINS.includes(domain)){notice.hidden=false;notice.textContent="Please use a corporate work email.";return}notice.hidden=true;document.getElementById("respondentRegisterForm").hidden=true;document.getElementById("respSuccessNotice").hidden=false}
function handleRespondentLogin(e){e.preventDefault();alert("Verification in progress for "+document.getElementById("login_email").value)}
function renderIndustries(){const grid=document.getElementById("industryGrid");if(!grid)return;CMS.industries.forEach((item,i)=>{const el=document.createElement("article");el.className="glass card";el.innerHTML=`<span class="section-label">${String(i+1).padStart(2,"0")}</span><h3 class="display" style="font-size:1.4rem;margin:12px 0 8px">${item.title}</h3><p style="color:#475569">${item.summary}</p><p style="color:#2563eb;font-weight:700">${item.description}</p>`;grid.appendChild(el)})}
function initHeroCanvas(){const canvas=document.getElementById("hero-canvas");if(!canvas)return;const ctx=canvas.getContext("2d");let width=canvas.width=innerWidth,height=canvas.height=innerHeight;const particles=Array.from({length:Math.floor(Math.min(width,1600)/24)},()=>({x:Math.random()*width,y:Math.random()*height,vx:(Math.random()-.5)*.4,vy:(Math.random()-.5)*.4,r:Math.random()*2+1}));let wave=0;function render(){ctx.clearRect(0,0,width,height);wave+=0.016;for(let j=0;j<4;j++){ctx.beginPath();ctx.moveTo(0,height*(0.28+j*0.16));for(let x=0;x<=width;x+=20)ctx.lineTo(x,height*(0.28+j*0.16)+Math.sin(x*0.0024+wave+j*0.7)*(26+j*10));ctx.strokeStyle=j===0?"rgba(37,99,235,.24)":"rgba(2,132,199,.16)";ctx.lineWidth=2.2;ctx.stroke()}particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=width;if(p.x>width)p.x=0;if(p.y<0)p.y=height;if(p.y>height)p.y=0;ctx.fillStyle="rgba(37,99,235,.4)";ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(render)}render();addEventListener("resize",()=>{width=canvas.width=innerWidth;height=canvas.height=innerHeight})}
function initPacing(){const canvas=document.getElementById("pacing-canvas");if(!canvas||!canvas.parentElement)return;const ctx=canvas.getContext("2d");let w=canvas.width=canvas.parentElement.clientWidth,h=canvas.height=canvas.parentElement.clientHeight,pulse=0;function render(){ctx.clearRect(0,0,w,h);pulse+=0.05;ctx.beginPath();const n=28;for(let i=0;i<n;i++){const x=(w/n)*i,y=h*0.5+Math.sin(pulse+i*0.3)*(h*0.25);i?ctx.lineTo(x,y):ctx.moveTo(x,y);ctx.fillStyle=i%4===0?"#38bdf8":"#2563eb";ctx.fillRect(x-1.5,y-1.5,3,3)}ctx.strokeStyle="#38bdf8";ctx.lineWidth=1.8;ctx.stroke();requestAnimationFrame(render)}render()}
function wireForms(){document.getElementById("rfpForm")?.addEventListener("submit",e=>{e.preventDefault();alert("Feasibility request received. SLA: under 2 hours.");e.target.reset()});document.getElementById("contactForm")?.addEventListener("submit",e=>{e.preventDefault();alert("Enquiry recorded.");e.target.reset()});document.getElementById("respondentModal")?.addEventListener("click",e=>{if(e.target.id==="respondentModal")closeRespondentModal()})}
document.addEventListener("DOMContentLoaded",()=>{renderIndustries();initHeroCanvas();initPacing();wireForms()});
